CREATE TABLE IF NOT EXISTS items_official (
  id             SERIAL PRIMARY KEY,
  tipo           VARCHAR(20)  NOT NULL,
  aeropuerto     VARCHAR(10),
  pais           VARCHAR(100) NOT NULL,
  item_en        TEXT         NOT NULL,
  item_es        TEXT         NOT NULL,
  precio         TEXT,
  descripcion_en TEXT,
  descripcion_es TEXT,
  notas          TEXT
);

INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'Travel Crate', 'Jaula de viaje', 'idem Tati', 'LATAM Pet Transport will provide a [tamaño] travel container.
Crate meets IATA regulations.', 'LATAM Pet Transport proporcionará una jaula de [tamaño]. 
La jaula cumple con la normativa IATA.', 'SI ES MAS DE UNA JAULA DEBERA SER PLURAL  : crates meet IATA regluaitons');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'Crate Pre-delivery', 'Pre-entrega de la jaula', 'idem retiro normal', 'Pre-delivery of the crate in [ORIGEN, city].', 'Pre-entrega de la jaula en [ORIGEN, ciudad].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'RNATT', 'RNATT', 'idem Tati + USD 50', 'Rabies Neutralising Rabies Titre Test.', 'Prueba de titulación de anticuerpos neutralizantes de la rabia', 'el microchip podria sera aparrteo no estar');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'Veterinary Fees', 'Honorarios veterinarios', 'idem Tati + USD 25', 'Vet visit, health certificate and de-worming treatment.', 'Visita al veterinario, certificado de salud y tratamiento de desparasitación.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'International Travel Certificate', 'Certificado internacional de viaje', 'USD190 x 1 mascota USD 290 por 2 mascotas y USD 390 por 3 mascotas', 'All legal paperwork to enter the pet(s) from Colombia into [destino, ciudad] 
Includes:
 - International health certificate endorsed by ICA', 'Todo el papeleo legal para ingresar la(s) mascota(s) de Colombia al [destino, ciudad]  incluye:  - Certificado de salud internacional avalado por el ICA', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'Collection / Pick-up', 'Retiro / Recogida', 'USD 200 ( 1 mascota en jaula grande o 2 chiquitas)', 'Collection from owner´s residence and transport to [codigo aeropuerto] airport.', 'Recogida en la residencia del propietario y transporte al aeropuerto [codigo aeropuerto].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'Airline Tender', 'Entrega a aerolínea', 'USD 120 siempre', 'Tender to the airline at [codigo aeropuerto] airport', 'Entrega a la aerolínea en el aeropuerto [código aeropuerto]', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'Air Freight', 'Flete aéreo', '+ USD 650 retail y USA + USD 750 si es agente.', 'This charge includes the air freight charged by the airline under the CARGO modality. Includes, also, all fees 
and taxes charged by the airline and by the official offices as well, such as Customs, ICA.
Includes agent fees needed to export the animals.
IMPORTANT:
The air freight has been estimated on this basis:  
[cantidad de jaulas] crates [tamaño de jaulas].
In case these estimations vary, we will have to re-estimate the air freight.
Routing: [codigo origen] - (posibles escalas, manual) - [codigo destino] on [aerolinea]''s flight  
ETA: TBC 
Frequency: TBC', 'Este cargo incluye el flete aéreo cobrado por la aerolínea bajo la modalidad CARGO. Incluye también todas las tasas e impuestos cobrados por la aerolínea y por las entidades oficiales, como Aduanas e ICA. Incluye los honorarios del agente necesarios para exportar los animales. 
IMPORTANTE: 
El flete aéreo se ha estimado sobre esta base: [cantidad de jaulas] jaulas [tamaño de jaulas]. En caso de que estas estimaciones varíen, tendremos que reestimar el flete aéreo. 
Ruta: [codigo origen] - (posibles escalas, manual) - [codigo destino] en el vuelo de [aerolinea]. 
ETA: Por confirmar. 
Frecuencia: Por confirmar.', 'el routing se modificara manualmente cada vez');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'LATAM Pet Transport Fee', 'Honorario LATAM Pet Transport', 'USD 350 siempre', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'Domestic Forwarding', 'Reenvío doméstico', 'a MDE, CLO, BAQ, PEI, AXM etc USD780 X 1 mascota, USD 880 X 2 mascotas y USD 980 x 3 mascotas  (INCLUYE HOME DELIVERY)', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Colombia', 'Boarding / Lodging', 'Hospedaje', 'USD 50 por perro x día y USD 40 por gato x día.  Si es solo una dia perro 80 gato 60', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'Travel Crate', 'Jaula de viaje', 'idem Tati', 'LATAM Pet Transport will provide a [tamaño] travel container.
Crate meets IATA regulations.', 'LATAM Pet Transport proporcionará una jaula de [tamaño]. 
La jaula cumple con la normativa IATA.', 'SI ES MAS DE UNA JAULA DEBERA SER PLURAL  : crates meet IATA regluaitons');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'Crate Pre-delivery', 'Pre-entrega de la jaula', 'idem retiro normal', 'Pre-delivery of the crate in [ORIGEN, city].', 'Pre-entrega de la jaula en [ORIGEN, ciudad].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'RNATT', 'RNATT', 'idem Tati +USD 50', 'Rabies Neutralising Rabies Titre Test.', 'Prueba de titulación de anticuerpos neutralizantes de la rabia', 'el microchip podria sera aparrteo no estar');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'Veterinary Fees', 'Honorarios veterinarios', 'idem Tati +USD 25', 'Vet visit, health certificate and de-worming treatment.', 'Visita al veterinario, certificado de salud y tratamiento de desparasitación.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'International Travel Certificate', 'Certificado internacional de viaje', 'USD220 x 1 mascota USD 280 por 2 mascotas y USD 340 por 3 mascotas', 'All legal paperwork to enter the pet(s) from Ecuador into [destino, ciudad] 
Includes:
 - International health certificate issued by Agrocalidad.', 'Toda la documentación legal para ingresar la(s) mascota(s) desde Ecuador a [destino, ciudad] 
Incluye:  
- Certificado sanitario internacional emitido por Agrocalidad.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'Collection / Pick-up', 'Retiro / Recogida', 'USD 200 ( 1 mascota en jaula grande o 2 chiquitas)', 'Collection from owner´s residence and transport to [codigo aeropuerto] airport.', 'Recogida en la residencia del propietario y transporte al aeropuerto [codigo aeropuerto].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'Airline Tender', 'Entrega a aerolínea', 'USD 120 siempre', 'Tender to the airline at [codigo aeropuerto] airport', 'Entrega a la aerolínea en el aeropuerto [código aeropuerto]', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'Air Freight', 'Flete aéreo', '+ USD 650 retail y USA + USD 750 si es agente.', 'This charge includes the air freight charged by the airline under the CARGO modality. Includes, also, all fees 
and taxes charged by the airline and by the official offices as well, such as Customs, health authorities.
Includes agent fees needed to export the animals.
IMPORTANT:
The air freight has been estimated on this basis:  
[cantidad de jaulas] crates [tamaño de jaulas].
In case these estimations vary, we will have to re-estimate the air freight.
Routing: [codigo origen] - (posibles escalas, manual) - [codigo destino] on [aerolinea]''s flight  
ETA: TBC 
Frequency: TBC', 'Este cargo incluye el flete aéreo cobrado por la aerolínea bajo la modalidad CARGO. Incluye también todas las tasas e impuestos cobrados por la aerolínea y por las entidades oficiales, como Aduanas e autoridades sanitarias. 
Incluye los honorarios del agente necesarios para exportar los animales. 
IMPORTANTE: 
El flete aéreo se ha estimado sobre esta base: [cantidad de jaulas] jaulas [tamaño de jaulas]. En caso de que estas estimaciones varíen, tendremos que reestimar el flete aéreo. 
Ruta: [codigo origen] - (posibles escalas, manual) - [codigo destino] en el vuelo de [aerolinea]. 
ETA: Por confirmar. 
Frecuencia: Por confirmar.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'LATAM Pet Transport Fee', 'Honorario LATAM Pet Transport', 'USD 350 siempre', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'Domestic Forwarding', 'Reenvío doméstico', 'a GYE, CUE  etc USD780 X 1 mascota, USD 880 X 2 mascotas y USD 980 x 3 mascotas', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Ecuador', 'Boarding / Lodging', 'Hospedaje', 'USD 50 por perro x día y USD 40 por gato x día.', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Travel Crate', 'Jaula de viaje', 'idem Aline', 'LATAM Pet Transport will provide a [tamaño] travel container.
Crate meets IATA regulations.', 'LATAM Pet Transport proporcionará una jaula de [tamaño]. 
La jaula cumple con la normativa IATA.', 'SI ES MAS DE UNA JAULA DEBERA SER PLURAL  : crates meet IATA regluaitons');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Crate Pre-delivery', 'Pre-entrega de la jaula', 'idem retiro normal', 'Pre-delivery of the crate in [ORIGEN, city].', 'Pre-entrega de la jaula en [ORIGEN, ciudad].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'RNATT', 'RNATT', 'idem Aline +USD 100', 'Rabies Neutralising Rabies Titre Test.', 'Prueba de titulación de anticuerpos neutralizantes de la rabia', 'el microchip podria sera aparrteo no estar');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Veterinary Fees', 'Honorarios veterinarios', 'USD250 x 1 mascota, USD 350 x 2 mascotas y USD 450 por 3 mascotas', 'Vet visit, health certificate and de-worming treatment.', 'Visita al veterinario, certificado de salud y tratamiento de desparasitación.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'International Travel Certificate – EU / South America', 'Certificado internacional de viaje – UE / Sudamérica', 'USD450 x 1 mascota USD 530 por 2 mascotas y USD 610 por 3 mascotas.', 'All legal paperwork issued in MAPA to enter the pet(s) from Brazil into [destino, ciudad] 
Includes:
 - International health certificate issued by MAPA', 'Todo el papeleo legal para ingresar la(s) mascota(s) de Brasil al [destino, ciudad]  incluye:  
- Certificado de salud internacional emitido por MAPA', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'International Travel Certificate – UK / USA', 'Certificado internacional de viaje – UK / USA', 'USD600 x 1 mascota USD 680 por 2 mascotas y USD 760 por 3 mascotas.', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Collection / Pick-up', 'Retiro / Recogida', 'USD 200 ( 1 mascota en jaula grande o 2 chiquitas/medianas) en Sao Paulo y USD 210 en Rio de Janeiro', 'Collection from owner´s residence and transport to [codigo aeropuerto] airport.', 'Recogida en la residencia del propietario y transporte al aeropuerto [codigo aeropuerto].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Airline Tender', 'Entrega a aerolínea', 'USD 120 siempre', 'Tender to the airline at [codigo aeropuerto] airport', 'Entrega a la aerolínea en el aeropuerto [código aeropuerto]', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Export Customs Clearance', 'Despacho aduanero de exportación', 'USD 480 hasta 2 mascotas, USD 580 x 3 mascotas.', 'Includes our charges, our customs agent''s charges and MAPA´s fees.', 'Incluye nuestros cargos, los cargos de nuestro agente de aduanas y los honorarios de MAPA.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Air Freight', 'Flete aéreo', '+ USD 900 retail  + USD 1000 si es agente.', 'This charge includes the air freight charged by the airline under the CARGO modality. Includes, also, all fees
and taxes charged by the airline and by the official offices as well, such as Customs, MAPA.
Includes agent fees needed to export the animals.
IMPORTANT:
The air freight has been estimated on this basis:  
[cantidad de jaulas] crates [tamaño de jaulas].
In case these estimations vary, we will have to re-estimate the air freight.
Routing: [codigo origen] - (posibles escalas, manual) - [codigo destino] on [aerolinea]''s flight  
ETA: TBC 
Frequency: TBC', 'Este cargo incluye el flete aéreo cobrado por la aerolínea bajo la modalidad CARGO. Incluye también todas las tasas e impuestos cobrados por la aerolínea y por las entidades oficiales, como Aduanas y MAPA. 
Incluye los honorarios del agente necesarios para exportar los animales. 
IMPORTANTE: 
El flete aéreo se ha estimado sobre esta base: [cantidad de jaulas] jaulas [tamaño de jaulas]. En caso de que estas estimaciones varíen, tendremos que reestimar el flete aéreo. 
Ruta: [codigo origen] - (posibles escalas, manual) - [codigo destino] en el vuelo de [aerolinea]. 
ETA: Por confirmar. 
Frecuencia: Por confirmar.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'LATAM Pet Transport Fee', 'Honorario LATAM Pet Transport', 'USD 350 siempre', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Domestic Forwarding', 'Reenvío doméstico', 'a cualquier ciudad del interior de Brasil 20% sobre el valor que cotiza Aline', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Brasil', 'Boarding / Lodging', 'Hospedaje', 'USD 50 por mascota por día. Si viaja a USA y viene de un traslado doméstico son mínimo 7 días de hospedaje. Si viaja a EU son 5 días.', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Travel Crate', 'Jaula de viaje', 'idem Adriana + USD 10', 'LATAM Pet Transport will provide a [tamaño] travel container.
Crate meets IATA regulations.', 'LATAM Pet Transport proporcionará una jaula de [tamaño]. 
La jaula cumple con la normativa IATA.', 'SI ES MAS DE UNA JAULA DEBERA SER PLURAL  : crates meet IATA regluaitons');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Crate Pre-delivery', 'Pre-entrega de la jaula', 'adri x 1,6', 'Pre-delivery of the crate in [ORIGEN, city].', 'Pre-entrega de la jaula en [ORIGEN, ciudad].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'RNATT', 'RNATT', 'idem Adriana +USD 100', 'Rabies Neutralising Rabies Titre Test.', 'Prueba de titulación de anticuerpos neutralizantes de la rabia', 'el microchip podria sera aparrteo no estar');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Veterinary Fees', 'Honorarios veterinarios', 'USD200 x 1 mascota, USD 260 x 2 mascotas y USD 340 por 3 mascotas', 'Vet visit, health certificate and de-worming treatment.', 'Visita al veterinario, certificado de salud y tratamiento de desparasitación.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'International Travel Certificate – Americas', 'Certificado internacional de viaje – América', 'DESTINO AMERICA  USD180 x 1 mascota USD 260 por 2 mascotas y USD 340 por 3 mascotas', 'All legal paperwork issued in SENASICA to enter the pet(s) from Mexico into [destino, ciudad] 
Includes:
 - International health certificate issued by SENASICA', 'Todo el papeleo legal para ingresar la(s) mascota(s) de Mexico al [destino, ciudad]  incluye:  
- Certificado de salud internacional emitido por SENASICA', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'International Travel Certificate – Non-Americas', 'Certificado internacional de viaje – No América', 'USD320 x 1 mascota USD 380 por 2 mascotas y USD 460 por 3 mascotas', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'EU Transit Certificate', 'Certificado de tránsito UE', 'USD 120 por pet', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Collection / Pick-up', 'Retiro / Recogida', 'USD 250 x 1,6 si entran en una sala camioneta', 'Collection from owner´s residence and transport to [codigo aeropuerto] airport.', 'Recogida en la residencia del propietario y transporte al aeropuerto [codigo aeropuerto].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Reception from Domestic Flight', 'Recepción de vuelo doméstico', 'adri x 1,6', 'Our personnel will pick up [cantidad y tipo de mascotas] at MEX Airport and transport to boarding facility in Mexico City.', 'Nuestro personal recogerá [cantidad y tipo de mascotas] en el Aeropuerto MEX y las transportará a la guardería en la Ciudad de México.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Airline Tender', 'Entrega a aerolínea', 'USD 120 siempre', 'Tender to the airline at [codigo aeropuerto] airport', 'Entrega a la aerolínea en el aeropuerto [código aeropuerto]', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Export Customs Clearance', 'Despacho aduanero de exportación', 'USD 255 siempre , no importa la cantidad de mascotas es por AWB .', 'Includes our charges, our customs agent''s charges and SENASICA´s fees.', 'Incluye nuestros cargos, los cargos de nuestro agente de aduanas y los honorarios de SENASICA.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Air Freight', 'Flete aéreo', '+ USD 1000 sobre Adriana', 'This charge includes the air freight charged by the airline under the CARGO modality. Includes, also, all fees
and taxes charged by the airline and by the official offices as well, such as Customs, SENASICA.
Includes agent fees needed to export the animals.
IMPORTANT:
The air freight has been estimated on this basis:  
[cantidad de jaulas] crates [tamaño de jaulas].
In case these estimations vary, we will have to re-estimate the air freight.
Routing: [codigo origen] - (posibles escalas, manual) - [codigo destino] on [aerolinea]''s flight  
ETA: TBC 
Frequency: TBC', 'Este cargo incluye el flete aéreo cobrado por la aerolínea bajo la modalidad CARGO. Incluye también todas las tasas e impuestos cobrados por la aerolínea y por las entidades oficiales, como Aduanas y SENASICA. 
Incluye los honorarios del agente necesarios para exportar los animales. 
IMPORTANTE: 
El flete aéreo se ha estimado sobre esta base: [cantidad de jaulas] jaulas [tamaño de jaulas]. En caso de que estas estimaciones varíen, tendremos que reestimar el flete aéreo. 
Ruta: [codigo origen] - (posibles escalas, manual) - [codigo destino] en el vuelo de [aerolinea]. 
ETA: Por confirmar. 
Frecuencia: Por confirmar.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'LATAM Pet Transport Fee', 'Honorario LATAM Pet Transport', 'USD 350 siempre', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Domestic Forwarding', 'Reenvío doméstico', 'a cualquier cuidad de Mexico hay que consaultar por Adriana y el costo es Adriana x 1,6', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Mexico', 'Boarding / Lodging', 'Hospedaje', 'USD 80 por mascota por día si es una noche , si es mas de una noce USD 60 por noche .', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'Travel Crate', 'Jaula de viaje', 'Interfamily  + USD 10', 'LATAM Pet Transport will provide a [tamaño] travel container.
Crate meets IATA regulations.', 'LATAM Pet Transport proporcionará una jaula de [tamaño]. 
La jaula cumple con la normativa IATA.', 'SI ES MAS DE UNA JAULA DEBERA SER PLURAL  : crates meet IATA regluaitons');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'Crate Pre-delivery', 'Pre-entrega de la jaula', 'idem retiro normal', 'Pre-delivery of the crate in [ORIGEN, city].', 'Pre-entrega de la jaula en [ORIGEN, ciudad].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'RNATT', 'RNATT', 'Interfamily +USD 150', 'Rabies Neutralising Rabies Titre Test.', 'Prueba de titulación de anticuerpos neutralizantes de la rabia', 'el microchip podria sera aparrteo no estar');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'Veterinary Fees', 'Honorarios veterinarios', 'USD200 x 1 mascota, USD 260 x 2 mascotas y USD 340 por 3 mascotas', 'Vet visit, health certificate and de-worming treatment.', 'Visita al veterinario, certificado de salud y tratamiento de desparasitación.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'International Travel Certificate – Americas', 'Certificado internacional de viaje – América', 'DESTINO AMERICA  USD320 x 1 mascota USD 450 por 2 mascotas y USD 450 por 3 mascotas', 'All legal paperwork issued in SAG to enter the pet(s) from Chile into [destino, ciudad] 
Includes:
 - International health certificate issued by SAG', 'Todo el papeleo legal para ingresar la(s) mascota(s) de Chile al [destino, ciudad]  incluye:  
- Certificado de salud internacional emitido por SAG', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'International Travel Certificate – Non-Americas', 'Certificado internacional de viaje – No América', 'USD350 x 1 mascota USD 410 por 2 mascotas y USD 470 por 3 mascotas', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'EU Transit Certificate', 'Certificado de tránsito UE', 'USD 120 por pet', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'Collection / Pick-up', 'Retiro / Recogida', 'USD 200 si entran en una sala camioneta', 'Collection from owner´s residence and transport to [codigo aeropuerto] airport.', 'Recogida en la residencia del propietario y transporte al aeropuerto [codigo aeropuerto].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'Airline Tender', 'Entrega a aerolínea', 'USD 120 siempre', 'Tender to the airline at [codigo aeropuerto] airport', 'Entrega a la aerolínea en el aeropuerto [código aeropuerto]', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'Air Freight', 'Flete aéreo', '+ USD 1000 sobre Interfamily', 'This charge includes the air freight charged by the airline under the CARGO modality. Includes, also, all fees
and taxes charged by the airline and by the official offices as well, such as Customs, SAG.
Includes agent fees needed to export the animals.
IMPORTANT:
The air freight has been estimated on this basis:  
[cantidad de jaulas] crates [tamaño de jaulas].
In case these estimations vary, we will have to re-estimate the air freight.
Routing: [codigo origen] - (posibles escalas, manual) - [codigo destino] on [aerolinea]''s flight  
ETA: TBC 
Frequency: TBC', 'Este cargo incluye el flete aéreo cobrado por la aerolínea bajo la modalidad CARGO. Incluye también todas las tasas e impuestos cobrados por la aerolínea y por las entidades oficiales, como Aduanas y SAG. 
Incluye los honorarios del agente necesarios para exportar los animales. 
IMPORTANTE: 
El flete aéreo se ha estimado sobre esta base: [cantidad de jaulas] jaulas [tamaño de jaulas]. En caso de que estas estimaciones varíen, tendremos que reestimar el flete aéreo. 
Ruta: [codigo origen] - (posibles escalas, manual) - [codigo destino] en el vuelo de [aerolinea]. 
ETA: Por confirmar. 
Frecuencia: Por confirmar.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'LATAM Pet Transport Fee', 'Honorario LATAM Pet Transport', 'USD 350 siempre', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'Domestic Forwarding', 'Reenvío doméstico', 'a cualquier cuidad de Chile hay que consaultar por Interfamily y el costo a cotizar es  x 1,6', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Chile', 'Boarding / Lodging', 'Hospedaje', 'USD 70 por mascota por día si es una noche , si es mas de una noche USD 50 por noche .', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Travel Crate', 'Jaula de viaje', 'Javier + USD 10', 'LATAM Pet Transport will provide a [tamaño] travel container.
Crate meets IATA regulations.', 'LATAM Pet Transport proporcionará una jaula de [tamaño]. 
La jaula cumple con la normativa IATA.', 'SI ES MAS DE UNA JAULA DEBERA SER PLURAL  : crates meet IATA regluaitons');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Crate Pre-delivery', 'Pre-entrega de la jaula', 'idem retiro normal', 'Pre-delivery of the crate in [ORIGEN, city].', 'Pre-entrega de la jaula en [ORIGEN, ciudad].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'RNATT', 'RNATT', 'Javier +USD 140', 'Rabies Neutralising Rabies Titre Test.', 'Prueba de titulación de anticuerpos neutralizantes de la rabia', 'el microchip podria sera aparrteo no estar');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Veterinary Fees', 'Honorarios veterinarios', 'USD150 x 1 mascota, USD 210 x 2 mascotas y USD 270 por 3 mascotas', 'Vet visit, health certificate and de-worming treatment.', 'Visita al veterinario, certificado de salud y tratamiento de desparasitación.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'International Travel Certificate – Americas', 'Certificado internacional de viaje – América', 'DESTINO AMERICA  USD280 x 1 mascota USD 360 por 2 mascotas y USD 440 por 3 mascotas', 'All legal paperwork issued in SENASA to enter the pet(s) from Costa Rica into [destino, ciudad] 
Includes:
 - International health certificate issued by SAG', 'Todo el papeleo legal para ingresar la(s) mascota(s) de Costa Rica al [destino, ciudad]  incluye:  
- Certificado de salud internacional emitido por SENASA', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'International Travel Certificate – Non-Americas', 'Certificado internacional de viaje – No América', 'USD280 x 1 mascota USD 360 por 2 mascotas y USD 440 por 3 mascotas', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'EU Transit Certificate', 'Certificado de tránsito UE', 'USD 120 por pet', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Collection / Pick-up', 'Retiro / Recogida', 'USD 200 si entran en una sala camioneta', 'Collection from owner´s residence and transport to [codigo aeropuerto] airport.', 'Recogida en la residencia del propietario y transporte al aeropuerto [codigo aeropuerto].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Airline Tender', 'Entrega a aerolínea', 'USD 120 siempre', 'Tender to the airline at [codigo aeropuerto] airport', 'Entregar a la aerolínea en el aeropuerto [codigo aeropuerto]', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Export Customs Clearance', 'Despacho aduanero de exportación', 'USD 205 siempre , no importa la cantidad de mascotas es por AWB .', 'Includes our charges, our customs agent''s charges and SENASA´s fees', 'Incluye nuestros cargos, los cargos de nuestro agente de aduanas y los honorarios de SENASA.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Air Freight', 'Flete aéreo', '+ USD 1000 sobre Javier', 'This charge includes the air freight charged by the airline under the CARGO modality. Includes, also, all fees
and taxes charged by the airline and by the official offices as well, such as Customs, SENASA.
Includes agent fees needed to export the animals.
IMPORTANT:
The air freight has been estimated on this basis:  
[cantidad de jaulas] crates [tamaño de jaulas].
In case these estimations vary, we will have to re-estimate the air freight.
Routing: [codigo origen] - (posibles escalas, manual) - [codigo destino] on [aerolinea]''s flight  
ETA: TBC 
Frequency: TBC', 'Este cargo incluye el flete aéreo cobrado por la aerolínea bajo la modalidad CARGO. Incluye, también, todas las tasas e impuestos cobrados por la aerolínea y por las oficinas oficiales, tales como Aduanas y SENASA. 
Incluye los honorarios del agente necesarios para exportar los animales. IMPORTANTE: El flete aéreo se ha estimado sobre esta base: [cantidad de jaulas] jaulas [tamaño de jaulas]. En caso de que estas estimaciones varíen, tendremos que volver a estimar el flete aéreo. Ruta: [codigo origen] - (posibles escalas, manual) - [codigo destino] en el vuelo de [aerolinea] ETA: Por confirmar Frecuencia: Por confirmar', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'LATAM Pet Transport Fee', 'Honorario LATAM Pet Transport', 'USD 350 siempre', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Domestic Forwarding', 'Reenvío doméstico', 'a cualquier cuidad de C Ricahay que consaultar por Javier y el costo  a cotizar es  x 1,6', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Costa Rica', 'Boarding / Lodging', 'Hospedaje', 'USD 40 por mascota por día si es una noche , si es mas de una noce USD 30 por noche .', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('TRANSITO', NULL, 'Chile / Argentina', 'Reception & Assistance During Connections', 'Recepción y asistencia en escalas', '350 USD', 'Reception and assistance for [cantidad] pet[s] at customs restricted area at [codigo aeropuerto donde se presta servicio] airport. We will clean crate, water and feed the pet[s] if needed. Service includes an hour of assitance and supervision', 'Recepción y asistencia para [cantidad] mascota[s] en el área restringida de aduanas en el aeropuerto [codigo aeropuerto donde se presta servicio]. Limpiaremos la jaula, daremos agua y alimentaremos a la[s] mascota[s] si es necesario. El servicio incluye una hora de asistencia y supervisión.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('TRANSITO', NULL, 'Chile / Argentina', 'Air Freight', 'Flete aéreo', 'proveedor + 1000 USD', 'This charge includes the air freight charged by the airline under the CARGO modality. Includes, also, all fees and taxes charged by the airline and by the official offices as well, such as Customs, healt autohorities.
Includes agent fees needed to export the animals.', 'Este cargo incluye el flete aéreo cobrado por la aerolínea bajo la modalidad de CARGA. Incluye, asimismo, todas las tasas e impuestos cobrados por la aerolínea y por las oficinas oficiales, tales como Aduanas y autoridades sanitarias. 
Incluye los honorarios del agente necesarios para exportar los animales.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('TRANSITO', NULL, 'Chile / Argentina', 'LATAM Pet Transport Fee', 'Honorario LATAM Pet Transport', '350 USD', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'Travel Crate', 'Jaula de viaje', 'tabla de precios', 'LATAM Pet Transport will provide a [tamaño] travel container.
Crate meets IATA regulations.', 'LATAM Pet Transport proporcionará una jaula de [tamaño]. 
La jaula cumple con la normativa IATA.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'Crate Pre-delivery', 'Pre-entrega de la jaula', 'Ver tabla de precios', 'Pre-delivery of the crate in [ORIGEN, city].', 'Pre-entrega de la jaula en [ORIGEN, ciudad].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'RNATT', 'RNATT', '1778 USD x 1 // 2068 USD x 2 // 2258 USD x 3', 'Rabies Neutralising Rabies Titre Test.', 'Prueba de titulación de anticuerpos neutralizantes de la rabia', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'Veterinary Fees', 'Honorarios veterinarios', 'Ver tabla de precios', 'Vet visit, health certificate and de-worming treatment.', 'Visita al veterinario, certificado de salud y tratamiento de desparasitación.', 'Para calcular precios | https://www.dropbox.com/home/2-%20Paises%20que%20sirve%20LATAM%20Pet%20Transport/1%20Paises%20LATAM%20Pet%20Transport/Argentina/Info%20para%20cotizar/Para%20cotizar%20al%20cliente');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'International Travel Certificate', 'Certificado internacional de viaje', 'Ver tabla de precios', 'All legal paperwork issued in SAG to enter the pet(s) from Chile into [destino, ciudad] 
Includes:
 - International health certificate issued by SAG', 'Todo el papeleo legal para ingresar la(s) mascota(s) de Chile al [destino, ciudad]  incluye:  
- Certificado de salud internacional emitido por SAG', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'Ground Transport', 'Transporte terrestre', 'no estimable', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'Collection / Pick-up', 'Retiro / Recogida', '180 USD (alerta: mirar tamano de jaulas para que entre en una camioneta  y dirección del cliente)', 'Collection from owner´s residence and transport to [codigo aeropuerto] airport.', 'Recogida en la residencia del propietario y transporte al aeropuerto [codigo aeropuerto].', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'Airline Tender', 'Entrega a aerolínea', 'USD 120 siempre', 'Tender to the airline at [codigo aeropuerto] airport', 'Entregar a la aerolínea en el aeropuerto [codigo aeropuerto]', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'Air Freight', 'Flete aéreo', 'cot de broker + 1000 USD', 'This charge includes the air freight charged by the airline under the CARGO modality. Includes, also, all fees
and taxes charged by the airline and by the official offices as well, such as Customs, SENASA.
Includes agent fees needed to export the animals.
IMPORTANT:
The air freight has been estimated on this basis:  
[cantidad de jaulas] crates [tamaño de jaulas].
In case these estimations vary, we will have to re-estimate the air freight.
Routing: [codigo origen] - (posibles escalas, manual) - [codigo destino] on [aerolinea]''s flight  
ETA: TBC 
Frequency: TBC', 'Este cargo incluye el flete aéreo cobrado por la aerolínea bajo la modalidad CARGO. Incluye, también, todas las tasas e impuestos cobrados por la aerolínea y por las oficinas oficiales, tales como Aduanas y SENASA. 
Incluye los honorarios del agente necesarios para exportar los animales. IMPORTANTE: El flete aéreo se ha estimado sobre esta base: [cantidad de jaulas] jaulas [tamaño de jaulas]. En caso de que estas estimaciones varíen, tendremos que volver a estimar el flete aéreo. Ruta: [codigo origen] - (posibles escalas, manual) - [codigo destino] en el vuelo de [aerolinea] 
ETA: Por confirmar 
Frecuencia: Por confirmar', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'Export Customs Clearance', 'Despacho aduanero de exportación', 'USD 200', 'Includes our charges, our customs agent''s charges and other fees.', 'Incluye nuestros cargos, los cargos de nuestro agente de aduanas y los otros honorarios.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('EXPO', NULL, 'Argentina', 'LATAM Pet Transport Fee', 'Honorario LATAM Pet Transport', 'Ver tabla de precios', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MIA', 'USA', 'Customs Clearance MIA airport', 'Despacho aduanero – Aeropuerto MIA', '1 pet: USD 575 | 2 pets: USD 605 | 3 pets: USD 635', 'Includes our charges, our customs agent''s charges and USDA''s fees.', 'Incluye nuestros cargos, los cargos de nuestro agente de aduanas y los honorarios de USDA.', 'Costo adicional USD 175 si es cachorro (formal entry requerida)');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MIA', 'USA', 'Home delivery', 'Entrega a domicilio', 'USD 225', 'Our personnel will transport pet(s) from MIA airport to client''s residence within city limits.', 'Nuestro personal transportará la(s) mascota(s) desde el aeropuerto MIA hasta la residencia del cliente dentro de los límites de la ciudad.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'EZE', 'Argentina', 'Customs Clearance EZE airport', 'Liberación de aduana – Aeropuerto EZE', '1 pet: USD 1,780 | 2 pets: USD 2,130 | 3 pets: USD 2,480 | 4 pets: USD 2,830', 'Includes our charges, our customs agent''s charges and Senasa''s fees. Service quoted Monday to Friday from 9 to 17pm.', 'Proceso de aprobación de la importación de animales vivos por parte de la Dirección Nacional de Aduana. Cotizado para arribos dentro del horario laboral de 8 am a 2 pm.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'EZE', 'Argentina', 'Mandatory fixed import taxes', 'Impuestos de importación fijos', '1 pet: USD 280 | 2 pets: USD 380 | 3 pets: USD 450 | 4 pets: USD 470', 'Argentina taxes the import of pet animals. Fixed amount charged by the Ministry of Agriculture, Livestock and Fisheries.', 'Valor fijo por la importación de mascotas arancelado por el Ministerio de Agricultura, Pesca y Ganadería.', 'No exemption possible. (Versión ESP 1 mascota: USD 230)');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'EZE', 'Argentina', 'POA (Power of Attorney)', 'Poder notarial (POA)', 'USD 0 | (online: USD 120)', 'The consignee must sign a POA in favor of our customs broker and have it notarized, in person or online.', 'El consignatario debe firmar un poder notarial a favor de nuestro agente de aduanas y notarizarlo, presencialmente u online.', 'If signed online: USD 120');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'EZE', 'Argentina', 'Variable import taxes (39% of CIF value)', 'Impuestos de importación variables (39% del valor CIF)', 'USD 0 (variable)', 'Applies only to puppies under 1 year old. Calculated as 39% of the CIF value declared on the AWB.', 'Aplica solo a cachorros menores de 1 año de edad. Se calcula como el 39% del valor CIF declarado en el AWB.', 'Not applicable unless puppies under 1 year old');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'EZE', 'Argentina', 'Home delivery', 'Entrega a domicilio', '1–3 pets: USD 180 | 4 pets: USD 380', 'Our personnel will transport pet(s) from EZE airport to client''s residence in Buenos Aires metro area. Monday to Friday from 9 to 17pm.', 'Entrega de la mascota y la jaula en el domicilio del cliente dentro del área metropolitana de Buenos Aires.', '4 pets: requiere van grande');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GIG', 'Brasil', 'Customs Clearance GIG airport', 'Liberación de aduana – Aeropuerto GIG', '1 pet: USD 1,110 | 2 pets: USD 1,140 | 3 pets: USD 1,200', 'Includes our charges, our customs agent''s charges and Mapa fees. IMPORTANT: if clearance is outside normal working days and hours, additional charges apply.', 'Proceso de aprobación de la importación de animales vivos por parte de Receita Federal. Cotizado para arribos dentro del horario laboral de 8 am a 5 pm.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GIG', 'Brasil', 'Warehouse and airport taxes', 'Impuestos de almacenaje y aeropuerto', '1 pet: USD 120 | 2 pets: USD 140 | 3 pets: USD 160', 'Includes Brazilian customs'' import tax for the animals import and warehouse charges at the airport.', 'Incluye las tasas de importación brasileñas para la importación de animales y los gastos de almacenaje en el aeropuerto.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GIG', 'Brasil', 'Import taxes Brazil (variable)', 'Impuestos de importación Brasil (variables)', 'USD 0 (variable)', 'Brazil taxes the import of pets. Total cost ~60% of airfreight and pet value. Legal exemptions exist for foreigners or Brazilians returning from abroad.', 'Impuestos a cobrar de acuerdo al valor declarado en la guía aérea (~60%). Consultar previa llegada de la mascota.', '~60% airfreight + pet value. Exemptions may apply (ver archivo adjunto)');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GIG', 'Brasil', 'Mandatory import taxes', 'Impuestos obligatorios', '1 pet: USD 80 | 2 pets: USD 160 | 3 pets: USD 240', 'Mandatory import taxes charged by Receita Federal.', 'Impuestos obligatorios recaudados por Receita Federal.', 'Charged by Receita Federal');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GIG', 'Brasil', 'Home delivery – Metro Rio de Janeiro', 'Entrega a domicilio – Gran Río de Janeiro', '1–2 pets: USD 210 | 3 pets: USD 270', 'LATAM personnel will transport pet(s) from GIG airport to client''s residence in Metro Rio de Janeiro.', 'Entrega de la mascota en el domicilio del cliente dentro del área metropolitana de Río de Janeiro.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GRU', 'Brasil', 'Customs Clearance GRU airport', 'Liberación de aduana – Aeropuerto GRU', '1 pet: USD 950 | 2 pets: USD 980 | 3 pets: USD 1,010', 'Includes our charges, our customs agent''s charges and Mapa fees. IMPORTANT: if clearance is outside normal working days and hours, additional charges apply.', 'Proceso de aprobación de la importación de animales vivos por parte de Receita Federal. Cotizado para arribos dentro del horario laboral de 8 am a 5 pm.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GRU', 'Brasil', 'Warehouse and airport taxes', 'Impuestos de almacenaje y aeropuerto', '1 pet: USD 170 | 2 pets: USD 190 | 3 pets: USD 240', 'Includes Brazilian customs'' import tax for the animals import and warehouse charges at the airport.', 'Incluye las tasas de importación brasileñas para la importación de animales y los gastos de almacenaje en el aeropuerto.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GRU', 'Brasil', 'Import taxes Brazil (variable)', 'Impuestos de importación Brasil (variables)', 'USD 0 (variable)', 'Brazil taxes the import of pets. Total cost ~60% of airfreight and pet value. Legal exemptions exist for foreigners or Brazilians returning from abroad.', 'Impuestos a cobrar de acuerdo al valor declarado en la guía aérea (~60%). Consultar previa llegada de la mascota.', '~60% airfreight + pet value. Exemptions may apply (ver archivo adjunto)');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'GRU', 'Brasil', 'Home delivery – Metro São Paulo', 'Entrega a domicilio – Gran São Paulo', '1–2 pets: USD 200 | 3 pets: USD 250', 'Home delivery to owner''s residence within São Paulo city limits.', 'Entrega de la mascota en el domicilio del cliente dentro del área metropolitana de São Paulo.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'VCP', 'Brasil', 'Customs Clearance VCP airport', 'Despacho de Aduana Aeropuerto VCP', '1 pet 1110 USD / 2 pets 1140 USD / 3 pets 1200 USD', 'Includes our charges, our customs agent''s charges and Mapa fees.', 'Incluye nuestros cargos, los de nuestro agente de aduanas y las tasas de Mapa.', 'Cargos extra por despacho después de las 13:30 y fines de semana.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'VCP', 'Brasil', 'Warehouse and airport taxes', 'Tasas de Almacén y Aeropuerto', '1 pet 120 USD / 2 pets 140 USD / 3 pets 160 USD', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'VCP', 'Brasil', 'Import taxes', 'Impuestos de Importación', '60 % of airfreight and pet value in AWB', '60 % of airfreight and pet value in AWB', '60 % del valor del flete aéreo y de la mascota en el AWB', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'VCP', 'Brasil', 'Mandatory import taxes', 'Impuestos de Importación Obligatorios', '1 pet 80 USD / 2 pets 160 USD / 3 pets 240 USD', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'VCP', 'Brasil', 'Home delivery', 'Entrega a domicilio', '1 pet 220 USD / 2 pets 220 USD / 3 pets 270 USD', NULL, NULL, NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'SCL', 'Chile', 'Customs Clearance', 'Liberación de aduana', '1 pet 980 USD / 2 pets 1100 USD / 3 pets 1220 USD', 'Includes our charges, our customs agent´s charges and SAG fees.', 'Incluye nuestros cargos, los cargos de nuestro agente y los impuestos de SAG', 'IMPORTANT: if clearance is outside normal working days and hours, we will need to add a surcharge. / IMPORTANTE: Si la liberación se realiza fuera de hora, se adicionará costo.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'SCL', 'Chile', 'Import taxes', 'Impuestos de Importación', '1-2 pets: 30% of the CIF value / 3 pets: 35% of the CIF value', 'Chile taxes the import of pets. Total cost is approx. 30-35% over CIF value + commercial value.', 'Chile cobra un impuesto por la importación de mascotas (30-35% del valor CIF + valor mascota).', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'SCL', 'Chile', 'Home delivery', 'Traslado a domicilio en Metro Santiago', '1 pet 180 USD / 2 pets 210 USD / 3 pets 280 USD', 'Home delivery to customer''s residence in Santiago metro area.', 'Entrega de la mascota en el domicilio del cliente dentro del área metropolitana.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'BOG', 'Colombia', 'Customs Clearance BOG airport', 'Liberación de aduana', '1 pet 1150 USD / 2 pets 1200 USD / 3 pets 1270 USD', 'Includes our charges, our customs agent''s charges and ICA´s fees.', 'Proceso de aprobación de la importación de animales vivos por parte de Aduana- Mincomercio.', 'Cotizado para arribos dentro del horario laboral (8 am a 2 pm).');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'BOG', 'Colombia', 'Import taxes in Colombia', 'Impuestos de importación', '35% CIF value declared on the AWB', 'Colombia taxes the import of pet animals. Total cost is approx. 35% over CIF value.', 'Impuestos a cobrar de acuerdo al valor declarado en la guía aérea (35% del valor CIF).', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'BOG', 'Colombia', 'Home delivery in Bogota metro area', 'Entrega en el domicilio', '1-2 pets 200 USD / 3 pets 250 USD', 'Home delivery to owner´s residence within city limits.', 'Entrega en el domicilio del propietario dentro de los límites de la ciudad.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'CLO', 'Colombia', 'Cargo Clearance CLO airport', 'Liberación de aduana', '1 pet 1150 USD / 2 pets 1200 USD / 3 pets 1270 USD', 'Includes our charges, our customs agent''s charges and ICA´s fees.', 'Proceso de aprobación de la importación de animales vivos por parte de Aduana- Mincomercio.', 'Cotizado para arribos dentro del horario laboral (8 am a 2 pm).');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'CLO', 'Colombia', 'Import taxes in Colombia', 'Impuestos de importación', '35% CIF value declared on the AWB', 'Colombia taxes the import of pet animals. Total cost is approx. 35% over CIF value.', 'Impuestos a cobrar de acuerdo al valor declarado en la guía aérea (35% del valor CIF).', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'CLO', 'Colombia', 'Home delivery in Cali metro area', 'Entrega en el domicilio', '200 USD', 'Home delivery to owner´s residence within city limits.', 'Entrega en el domicilio del propietario dentro de los límites de la ciudad.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'SJO', 'Costa Rica', 'Customs Clearance', 'Liberación de Aduana', '1 pet: USD 700 / 2 pets: USD 800 / 3 pets: USD 880', 'Includes our charges, our customs agent''s charges and Senasa''s fees. Does not include the Costa Rican Customs'' import tax for the animal''s import.', 'Incluye nuestros costos, los costos de nuestro agente y los costos de SENASA. No incluye los costos de aduana de Costa Rica por importación de animales.', 'Surcharge between USD 50 and USD 200 if clearance is outside normal working days and hours.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'SJO', 'Costa Rica', 'SENASA fees', 'Impuestos de SENASA', 'USD 180', 'Senasa charges for the import of live animals and vet inspection upon arrival.', 'Senasa cobra un impuesto por la importación de animales vivos y su inspección veterinaria al arribar.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'SJO', 'Costa Rica', 'Import taxes', 'Impuestos de Importación', '24.5% of the CIF value reflected on the AWB', '24.5% of the CIF value reflected on the AWB.', '24.5% del valor CIF declarado en AWB.', 'Final confirmation once we receive final AWB.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'SJO', 'Costa Rica', 'Home delivery in San Jose metro', 'Entrega en domicilio en San José metro', '1 pet: USD 150 / 2 pets: USD 200 / 3 pets: USD 220', 'LATAM Pet Transport will transport pets from SJO airport to client''s residence in San Jose metro area.', 'Traslado de la(s) mascota(s) desde el aeropuerto de SJO a la residencia del cliente en el área metropolitana de San José.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'UIO', 'Ecuador', 'Customs clearance', 'Liberación de aduana', '1 pet: USD 890 / 2 pets: USD 940 / 3 pets: USD 990', 'Includes our charges, our customs agent''s charges and Agrocalidad''s fees. Does not include the Ecuadorian Customs'' import tax for the animal''s import.', 'Proceso de aprobación de la importación de animales vivos por parte del Servicio Nacional de Aduana del Ecuador (SENAE). Cotizado para arribos dentro del horario laboral de 8 am a 8 pm.', 'Documents and information must be received 48 hs before pets arrival.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'UIO', 'Ecuador', 'Import taxes in Ecuador', 'Impuestos de importación', '43% of airfreight and pet value in AWB', 'Ecuador taxes the import of pet animals. Total cost is approximately 43% of CIF value.', 'Impuestos a cobrar de acuerdo al valor declarado en la guía aérea (43%).', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'UIO', 'Ecuador', 'Import Formalities', 'Trámites de importación', 'USD 370', 'Import tariff rights and service fees.', 'Derechos arancelarios y tasas por servicios de importación.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'UIO', 'Ecuador', 'Warehouse', 'Acceso a la bodega', '1 pet: USD 90 / 2 pets: USD 120 / 3 pets: USD 150', 'Pet(s) will be placed in airport''s warehouse during custom clearance.', 'Tarifa aplicada por acceso a la bodega. La mascota permanecerá en la bodega durante el proceso de liberación de aduana.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'UIO', 'Ecuador', 'Health Authorities fees (Agrocalidad)', 'Agrocalidad', '1 pet: USD 190 / 2 pets: USD 210 / 3 pets: USD 230', 'Fees charged by Health Authorities at the airport.', 'Inspección sanitaria por parte de un profesional veterinario de Agrocalidad al ingreso al país.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'UIO', 'Ecuador', 'Home delivery', 'Entrega en el domicilio', '1 pet: USD 250 / 2 pets: USD 280 / 3 pets: USD 310', 'Pick up from UIO airport and delivery to owner''s residence in Quito metro area.', 'Entrega de la mascota en el domicilio del cliente dentro del área metropolitana de Quito.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MEX', 'México', 'Customs Clearance MEX airport', 'Liberación de Aduana en Aeropuerto de MEX', '1 pet: USD 1,200 / 2 pets: USD 1,430 / 3 pets: USD 1,680 / 4 pets: USD 1,830 (Puppy 1 pet: USD 1,600)', 'Includes our charges, our customs agent''s charges and health authorities fees (SENASICA).', 'Incluye nuestros costos, los costos de nuestro agente y los costos de SENASICA. No incluye los costos de aduana de México por importación de animales.', 'Surcharge applies if clearance is outside normal working days and hours.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MEX', 'México', 'Import taxes Mexico', 'Impuestos de Importación México', '20% of the CIF value', 'Mexico taxes the import of pets. Total cost is approximately 20% over CIF value + commercial value of the pet.', 'México grava la importación de mascotas. El costo total es aproximadamente un 20% superior al valor CIF más el valor comercial de la mascota.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MEX', 'México', 'IGI import tax', 'Impuesto IGI', '16% applicable; exempt only with valid certificate from the U.S., Canada, U.K., or Europe', '16% applicable; exempt only with valid certificate from the U.S., Canada, U.K., or Europe.', '16% aplicable; exento solo con certificado válido de EE. UU., Canadá, Reino Unido o Europa.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MEX', 'México', 'Airline fee to transfer to Warehouse', 'Impuesto a la aerolínea — transferencia a bodega', '1 pet: USD 180 / 2 pets: USD 230 / 3 pets: USD 280 / 4 pets: USD 320', 'Airline fee to transfer to the warehouse at the airport so pets can be assisted.', 'Impuesto a la aerolínea para la transferencia a la bodega en el aeropuerto para asistir a las mascotas.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MEX', 'México', 'Warehouse Access', 'Acceso a la bodega', '1 pet: USD 120 / 2 pets: USD 140 / 3 pets: USD 160 / 4 pets: USD 180', 'The pet will be in the warehouse until the customs clearing process is completed.', 'La mascota permanecerá en la bodega hasta que se complete la liberación de aduana.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MEX', 'México', 'Home delivery in Metro Mexico City', 'Entrega en Domicilio en Ciudad de México', '1 pet: USD 280 / 2 pets: USD 300 / 3 pets: USD 350 / 4 pets: USD 400', 'Transport from MEX airport to client''s residence in metro Mexico City.', 'Nuestro personal entregará la(s) mascota(s) en el domicilio del cliente en Ciudad de México.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'PTY', 'Panamá', 'Customs Clearance PTY airport', 'Liberación de Aduana — Aeropuerto PTY', '1 pet: USD 856 / 2 pets: USD 956 / 3 pets: USD 1,056', 'Includes our charges, our customs agent''s charges and MINSA/MIDA''s fees.', 'Incluye nuestros costos, los costos de nuestro agente aduanero y los costos de MINSA/MIDA.', 'USD 250 extra fee applies for flight arrival after 4:30 pm.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'PTY', 'Panamá', 'Home quarantine', 'Cuarentena domiciliaria', '1 pet: USD 146 / 2 pets: USD 196 / 3 pets: USD 246', 'Authorization issued by MINSA for home quarantine.', 'Autorización emitida por MINSA para cuarentena domiciliaria.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'PTY', 'Panamá', 'Home delivery in Panama metro area', 'Entrega en domicilio — área metropolitana de Panamá', '1 pet: USD 230 / 2 pets: USD 230 / 3 pets: USD 280', 'Home delivery to owner''s residence within city limits.', 'Entrega de la mascota en el domicilio del cliente dentro del área metropolitana.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'LIM', 'Perú', 'Cargo Clearance LIM airport', 'Liberación de aduana — Aeropuerto LIM', '1 pet: USD 1,050 / 2 pets: USD 1,170 / 3 pets: USD 1,300', 'Includes our charges, our customs agent''s charges and Senasa''s fees. Does not include Peru''s Customs import tax for the animal''s import.', 'Proceso de aprobación de la importación de animales vivos por parte de Aduana-SUNAT. No incluye impuestos de aduana del Perú para la importación de animales.', 'Extra fees apply for any arrival after 1:30 pm.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'LIM', 'Perú', 'Import taxes Peru', 'Impuestos de importación', '35% of CIF value (applies from the 2nd pet if not exempted)', 'Peru taxes the import of pet animals. Total cost is approximately 35% over CIF value, applies on the 2nd pet.', 'Impuestos a cobrar de acuerdo al valor declarado en la guía aérea (35%). Se aplica a partir de la 2ª mascota si no está exenta.', '35% of CIF value will apply if not exempted on the 2nd pet.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'LIM', 'Perú', 'Home delivery in Lima', 'Entrega en el domicilio', '1 pet: USD 200 / 2 pets: USD 200 / 3 pets: USD 250', 'LATAM Pet Transport personnel will transport pets from LIM airport to client''s residence in Lima metro area.', 'Entrega de la mascota en el domicilio del cliente dentro del área metropolitana de Lima.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MVD', 'Uruguay', 'Customs Clearance MVD airport', 'Liberación de aduana — Aeropuerto MVD', '1 pet: USD 1,150 / 2 pets: USD 1,200 / 3 pets: USD 1,250', 'Includes our charges, our customs agent''s charges and MGAP''s fees. Does not include Uruguay Customs'' import tax for the animal''s import.', 'Proceso de aprobación de la importación de animales vivos por parte de la Dirección Nacional de Aduana. No incluye impuestos de aduana de Uruguay para la importación de animales.', 'Quoted Mon–Fri until 1:30 pm. Extra charges apply for after-hours and weekend arrivals.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MVD', 'Uruguay', 'Import taxes MVD', 'Impuestos de importación', '1 pet: USD 170 / 2 pets: USD 220 / 3 pets: USD 270', '35% of the CIF value is a must and will apply.', 'Valor fijo por la importación de mascotas en Uruguay (equivalente al 35% del valor CIF).', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'MVD', 'Uruguay', 'Home delivery in Montevideo', 'Entrega en el domicilio', 'USD 210 (1–3 pets)', 'Pick up from MVD airport and delivery to owner''s residence in Montevideo metro area.', 'Entrega de la mascota en el domicilio del cliente dentro del área metropolitana de Montevideo.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'CUN', 'México', 'Customs Clearance CUN airport', 'Liberación de Aduana — Aeropuerto CUN', '1 pet: USD 1,350 / 2 pets: USD 1,500 / 3 pets: USD 1,650', 'Includes our charges, our customs agent''s charges and health authorities fees (SENASICA).', 'Incluye nuestros costos, los costos de nuestro agente y los costos de SENASICA.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'CUN', 'México', 'Warehouse Access', 'Acceso a la Bodega', '1 pet: USD 190 / 2 pets: USD 240 / 3 pets: USD 290', 'Pets will be placed in warehouse until customs clearing process is finished.', 'La mascota permanecerá en la bodega hasta que se complete la liberación de aduana.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'CUN', 'México', 'Import taxes Mexico', 'Impuestos de Importación en México', '30% of airfreight and pet value on AWB', 'Subject to pets value declared on AWB.', '30% del valor de la guía aérea. Sujeto a la valuación de la mascota.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'CUN', 'México', 'Home delivery (zone-based)', 'Entrega en domicilio (por zona)', 'Metro Cancún: 1 pet USD 200 / 2 pets USD 200 / 3 pets USD 250 | Puerto Morelos: 1 pet USD 300 / 2 pets USD 250 / 3 pets USD 300 | Playa del Carmen: USD 400 | Tulum: USD 500 | Cozumel: 1-2 pets USD 500 / 3 pets USD 550 + ferry | Isla Mujeres: USD 500 + ferry', 'Transport from CUN airport to client''s residence. Price varies by delivery zone.', 'Traslado desde el aeropuerto CUN al domicilio del cliente. El precio varía según la zona de entrega.', 'Cozumel and Isla Mujeres: additional ferry fees apply.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'ASU', 'Paraguay', 'Customs Clearance ASU airport', 'Liberación de aduana — Aeropuerto ASU', '1 pet: USD 980 / 2 pets: USD 1,150 / 3 pets: USD 1,410', 'Includes our charges, our customs agent''s charges and SENACSA''s fees. Does not include Paraguay''s Customs import tax.', 'Proceso de aprobación de la importación de animales vivos por parte de la Dirección Nacional de Aduana. Cotizado para arribos dentro del horario laboral de 7:30 am a 5 pm.', 'Outside M–F 8:00–17:00: 1 pet USD 500 / 2 pets USD 1,100 / 3 pets USD 1,400 surcharge.');
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'ASU', 'Paraguay', 'Import taxes Paraguay', 'Impuestos de importación', '1 pet: USD 250 / 2 pets: USD 300 / 3 pets: USD 350', 'Paraguay taxes the import of pet animals with a fixed amount.', 'Valor fijo por la importación de mascotas arancelado por el Ministerio de Agricultura, Pesca y Ganadería.', NULL);
INSERT INTO items_official (tipo, aeropuerto, pais, item_en, item_es, precio, descripcion_en, descripcion_es, notas) VALUES ('IMPO', 'ASU', 'Paraguay', 'Home delivery', 'Entrega en el domicilio', '1 pet: USD 150 / 2 pets: USD 150 / 3 pets: USD 180', 'LATAM Pet Transport will deliver pets to owner''s residence within city limits. Quoted in normal working hours M–F 9:00–17:00.', 'Entrega de la mascota en el domicilio del cliente dentro del área metropolitana de Asunción.', NULL);
