CREATE TABLE IF NOT EXISTS breeds (
  id SERIAL PRIMARY KEY,
  name_es VARCHAR(150) NOT NULL,
  name_en VARCHAR(150) NOT NULL,
  type VARCHAR(20) NOT NULL,
  braqui BOOLEAN NOT NULL DEFAULT FALSE,
  danger BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Affenpinscher', 'Affenpinscher', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('American Bully', 'American Bully', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Boston Terrier', 'Boston Terrier', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bóxer', 'Boxer', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Grifón de Bruselas', 'Brussels Griffon', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bulldog Inglés', 'English Bulldog', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bulldog Francés', 'French Bulldog', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bulldog Americano', 'American Bulldog', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bullmastiff', 'Bullmastiff', 'perro', true, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cane Corso / Mastín Italiano', 'Cane Corso (Italian Mastiff)', 'perro', true, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cavalier King Charles Spaniel', 'Cavalier King Charles Spaniel', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Chow Chow', 'Chow Chow', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Dogo de Burdeos', 'Dogue de Bordeaux (Bordeaux Mastiff)', 'perro', true, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Spaniel Inglés de Juguete', 'English Toy Spaniel', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Chin Japonés', 'Japanese Chin', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Lhasa Apso', 'Lhasa Apso', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Mastín Napolitano', 'Neapolitan Mastiff', 'perro', true, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pequinés', 'Pekingese', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Carlino / Pug', 'Pug', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Shar Pei', 'Shar Pei', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Shih Tzu', 'Shih Tzu', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Spaniel Tibetano', 'Tibetan Spaniel', 'perro', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('American Pit Bull Terrier', 'American Pit Bull Terrier', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('American Staffordshire Terrier', 'American Staffordshire Terrier', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Staffordshire Bull Terrier', 'Staffordshire Bull Terrier', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bull Terrier', 'Bull Terrier', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Rottweiler', 'Rottweiler', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Doberman Pinscher', 'Doberman Pinscher', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Dogo Argentino', 'Dogo Argentino', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Fila Brasileño', 'Fila Brasileiro', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Tosa Inu / Tosa Japonés', 'Japanese Tosa (Tosa Inu)', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Presa Canario / Dogo Canario', 'Presa Canario (Dogo Canario)', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Akita Inu / Akita Americano', 'Akita Inu / American Akita', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Mastín Inglés', 'English Mastiff', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor del Cáucaso', 'Caucasian Shepherd Dog', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Karabash / Pastor de Anatolia', 'Karabash (Anatolian Shepherd)', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Híbrido de Lobo', 'Wolf-dog Hybrid', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bandog', 'Bandog', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Ca de Bou / Perro de Presa Mallorquín', 'Ca de Bou (Majorcan Mastiff)', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Labrador Retriever', 'Labrador Retriever', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Golden Retriever', 'Golden Retriever', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor/Ovejero Alemán', 'German Shepherd', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Caniche / Poodle', 'Poodle', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Beagle', 'Beagle', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Dachshund / Teckel', 'Dachshund', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Yorkshire Terrier', 'Yorkshire Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Chihuahua', 'Chihuahua', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Maltés', 'Maltese', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Schnauzer Miniatura', 'Miniature Schnauzer', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Schnauzer Estándar', 'Standard Schnauzer', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Schnauzer Gigante', 'Giant Schnauzer', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cocker Spaniel Inglés', 'English Cocker Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cocker Spaniel Americano', 'American Cocker Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Springer Spaniel Inglés', 'English Springer Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Border Collie', 'Border Collie', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Collie de pelo largo', 'Rough Collie', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Collie de pelo corto', 'Smooth Collie', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Shetland Sheepdog', 'Shetland Sheepdog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor Australiano', 'Australian Shepherd', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Husky Siberiano', 'Siberian Husky', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Malamute de Alaska', 'Alaskan Malamute', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Samoyedo', 'Samoyed', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Spitz Alemán / Pomerania', 'Pomeranian', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Spitz Japonés', 'Japanese Spitz', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Shiba Inu', 'Shiba Inu', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Gran Danés', 'Great Dane', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('San Bernardo', 'Saint Bernard', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Leonberger', 'Leonberger', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Terranova', 'Newfoundland', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor de Berna / Boyero de Berna', 'Bernese Mountain Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Gran Pirineo / Montaña de los Pirineos', 'Great Pyrenees', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Weimaraner', 'Weimaraner', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Vizsla', 'Vizsla', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Braco Alemán de pelo corto', 'German Shorthaired Pointer', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Braco Alemán de pelo duro', 'German Wirehaired Pointer', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pointer Inglés', 'English Pointer', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Setter Irlandés', 'Irish Setter', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Setter Inglés', 'English Setter', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Setter Gordon', 'Gordon Setter', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Basset Hound', 'Basset Hound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bloodhound / Sabueso de San Huberto', 'Bloodhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Galgo Inglés / Greyhound', 'Greyhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Galgo Español', 'Spanish Greyhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Whippet', 'Whippet', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Borzoi / Galgo Ruso', 'Borzoi', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Saluki', 'Saluki', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Afghan Hound / Galgo Afgano', 'Afghan Hound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Rhodesian Ridgeback', 'Rhodesian Ridgeback', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Dálmata', 'Dalmatian', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Caniche Toy', 'Toy Poodle', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Caniche Miniatura', 'Miniature Poodle', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('West Highland White Terrier', 'West Highland White Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Scottish Terrier', 'Scottish Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cairn Terrier', 'Cairn Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Jack Russell Terrier', 'Jack Russell Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Parson Russell Terrier', 'Parson Russell Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Fox Terrier de pelo liso', 'Smooth Fox Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Fox Terrier de pelo duro', 'Wire Fox Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Airedale Terrier', 'Airedale Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bedlington Terrier', 'Bedlington Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Welsh Terrier', 'Welsh Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Irish Terrier', 'Irish Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Lakeland Terrier', 'Lakeland Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Norfolk Terrier', 'Norfolk Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Norwich Terrier', 'Norwich Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Dandie Dinmont Terrier', 'Dandie Dinmont Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Miniature Pinscher', 'Miniature Pinscher', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pinscher Alemán', 'German Pinscher', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Hovawart', 'Hovawart', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor Belga Malinois', 'Belgian Malinois', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor Belga Tervueren', 'Belgian Tervuren', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor Belga Groenendael', 'Belgian Sheepdog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor Belga Laekenois', 'Belgian Laekenois', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor de Shetland', 'Shetland Sheepdog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bouvier de Flandes', 'Bouvier des Flandres', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Boyero de Berna', 'Bernese Mountain Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Entlebucher', 'Entlebucher Mountain Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Appenzeller', 'Appenzeller Sennenhund', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Boyero de Appenzell', 'Appenzell Cattle Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Corgi Galés de Pembroke', 'Pembroke Welsh Corgi', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Corgi Galés de Cardigan', 'Cardigan Welsh Corgi', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Australian Cattle Dog / Blue Heeler', 'Australian Cattle Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Australian Kelpie', 'Australian Kelpie', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Labradoodle', 'Labradoodle', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Goldendoodle', 'Goldendoodle', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cockapoo', 'Cockapoo', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bichón Frisé', 'Bichon Frise', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bichón Habanero', 'Havanese', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bichón Boloñés', 'Bolognese', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bichón Maltés', 'Maltese', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cotón de Tuléar', 'Coton de Tulear', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Löwchen', 'Lowchen', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Papillón', 'Papillon', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Phalène', 'Phalene', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Galgo Italiano', 'Italian Greyhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('King Charles Spaniel', 'King Charles Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Toy Fox Terrier', 'Toy Fox Terrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Spitz Enano / Pomerania', 'Pomeranian', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Basenji', 'Basenji', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro Sin Pelo del Perú', 'Peruvian Inca Orchid', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Xoloitzcuintle', 'Xoloitzcuintli', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cirneco del Etna', 'Cirneco dell''Etna', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Podenco Ibicenco', 'Ibizan Hound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pharaoh Hound / Kelb tal-Fenek', 'Pharaoh Hound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro de agua español', 'Spanish Water Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro de agua portugués', 'Portuguese Water Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Poodle Grande / Caniche Grande', 'Standard Poodle', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Lagotto Romagnolo', 'Lagotto Romagnolo', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Barbet', 'Barbet', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Irish Water Spaniel', 'Irish Water Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Curly-Coated Retriever', 'Curly-Coated Retriever', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Flat-Coated Retriever', 'Flat-Coated Retriever', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Nova Scotia Duck Tolling Retriever', 'Nova Scotia Duck Tolling Retriever', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Chesapeake Bay Retriever', 'Chesapeake Bay Retriever', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Sussex Spaniel', 'Sussex Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Clumber Spaniel', 'Clumber Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Field Spaniel', 'Field Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Welsh Springer Spaniel', 'Welsh Springer Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Boykin Spaniel', 'Boykin Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Braco Italiano', 'Italian Pointer (Bracco Italiano)', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Spinone Italiano', 'Italian Spinone', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Epagneul Breton / Bretón', 'Brittany Spaniel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Kuvasz', 'Kuvasz', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Komondor', 'Komondor', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Puli', 'Puli', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pumi', 'Pumi', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Mudi', 'Mudi', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor de las Llanuras de Hungría', 'Puli', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Ovcharka del Asia Central', 'Central Asian Shepherd Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro de Montana del Pirineo', 'Pyrenean Mastiff', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Mastín Español', 'Spanish Mastiff', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro de Pastor de los Alpes', 'Bernese Mountain Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Alano Español', 'Spanish Alano', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Dogo Brasileño / Fila', 'Brazilian Mastiff', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Rafeiro do Alentejo', 'Alentejo Mastiff', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cão de Castro Laboreiro', 'Castro Laboreiro Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Ovejero Magallánico', 'Patagonian Sheepdog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro sin pelo peruano', 'Peruvian Hairless Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Fila de São Miguel', 'Azores Cattle Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Basenji', 'Basenji', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Sloughi', 'Sloughi', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Azawakh', 'Azawakh', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Ibizan Hound', 'Ibizan Hound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Harrier', 'Harrier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('American Foxhound', 'American Foxhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('English Foxhound', 'English Foxhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Otterhound', 'Otterhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Plott Hound', 'Plott Hound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Treeing Walker Coonhound', 'Treeing Walker Coonhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Redbone Coonhound', 'Redbone Coonhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Black and Tan Coonhound', 'Black and Tan Coonhound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Schipperke', 'Schipperke', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Keeshond', 'Keeshond', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Spitz Finlandés', 'Finnish Spitz', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Lapphund Finlandés', 'Finnish Lapphund', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Lapphund Sueco', 'Swedish Lapphund', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro de Groenlandia', 'Greenland Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Akita Americano', 'American Akita', 'perro', false, true);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Kai Ken', 'Kai Ken', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Kishu Ken', 'Kishu Ken', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Hokkaido', 'Hokkaido', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Shikoku', 'Shikoku', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Jindo Coreano', 'Korean Jindo', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pastor de Europa del Este', 'East European Shepherd', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Laika de Siberia Occidental', 'West Siberian Laika', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Laika de Siberia Oriental', 'East Siberian Laika', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Eurasier', 'Eurasier', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Canaan Dog', 'Canaan Dog', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro de caza de África del Sur', 'South African Boerboel', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Perro de Caza del Faraón', 'Pharaoh Hound', 'perro', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Persa', 'Persian', 'gato', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Exótico de pelo corto', 'Exotic Shorthair', 'gato', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Himalayo', 'Himalayan', 'gato', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Burmés', 'Burmese', 'gato', true, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Ragdoll', 'Ragdoll', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Maine Coon', 'Maine Coon', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Siamés', 'Siamese', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bengalí', 'Bengal', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Abisinio', 'Abyssinian', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Sphynx / Esfinge', 'Sphynx', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Scottish Fold', 'Scottish Fold', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('British Shorthair', 'British Shorthair', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('British Longhair', 'British Longhair', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Noruego del Bosque', 'Norwegian Forest Cat', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Siberiano', 'Siberian', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Turco Van', 'Turkish Van', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Turco Angora', 'Turkish Angora', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Angora', 'Angora', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Balinés', 'Balinese', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Javanés', 'Javanese', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Oriental de pelo corto', 'Oriental Shorthair', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Oriental de pelo largo', 'Oriental Longhair', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Tonkinés', 'Tonkinese', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Birmano Sagrado / Sagrado de Birmania', 'Birman', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Ragamuffin', 'Ragamuffin', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Chartreux', 'Chartreux', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Azul Ruso', 'Russian Blue', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Korat', 'Korat', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Singapura', 'Singapura', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Ocicato', 'Ocicat', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Snowshoe', 'Snowshoe', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('American Shorthair', 'American Shorthair', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('American Wirehair', 'American Wirehair', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('American Curl', 'American Curl', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('American Bobtail', 'American Bobtail', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Munchkin', 'Munchkin', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('LaPerm', 'LaPerm', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Devon Rex', 'Devon Rex', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cornish Rex', 'Cornish Rex', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Selkirk Rex', 'Selkirk Rex', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('German Rex', 'German Rex', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Gato del Egeo', 'Aegean', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Gato de Van', 'Van Cat', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Savannah', 'Savannah', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Chausie', 'Chausie', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Serengeti', 'Serengeti', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Pixie-bob', 'Pixie-Bob', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Japonés Bobtail', 'Japanese Bobtail', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Kurilian Bobtail', 'Kurilian Bobtail', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Manx', 'Manx', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Cymric', 'Cymric', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Peterbald', 'Peterbald', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Don Sphynx / Donskoy', 'Donskoy (Don Sphynx)', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Lykoi / Gato Hombre Lobo', 'Lykoi', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Toyger', 'Toyger', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Bombay', 'Bombay', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Habana', 'Havana Brown', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Nebelung', 'Nebelung', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Egyptian Mau', 'Egyptian Mau', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Somali', 'Somali', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Tiffanie', 'Tiffanie', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Burmilla', 'Burmilla', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Chinchilla (gato)', 'Chinchilla Persian', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Gato de pelo largo doméstico', 'Domestic Longhair', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Gato de pelo corto doméstico', 'Domestic Shorthair', 'gato', false, false);
INSERT INTO breeds (name_es, name_en, type, braqui, danger) VALUES ('Mestizo', 'Mixed Breed', 'perro', false, false);
